#cloud-config
groups:
  - docker
users:
  - name: ${username}
    groups: sudo
    shell: /bin/bash
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    ssh_authorized_keys:
      - ${ssh_public_key}
package_update: true
package_upgrade: false
packages:
  - sudo
  - git
  - curl
  - ca-certificates
runcmd:
# Install docker
  - curl -fsSL https://get.docker.com -o get-docker.sh
  - sudo sh get-docker.sh
 # Add user to group Docker
  - sudo usermod -aG docker ${username}  
